
AllCops:
  NewCops: enable

inherit_from: .rubocop_todo.yml

Style/FrozenStringLiteralComment:
  Exclude:
    - db/schema.rb
Style/NumericLiterals:
  Exclude:
    - db/schema.rb
Style/StringLiterals:
  Exclude:
    - db/schema.rb